# --- Basic Site Settings ---
locale      : "en-US"
site_theme  : "default"   # 想更清爽可用 "air"
title       : "Ling Aowei"
title_separator : "-"
name        : &name "Ling Aowei"
description : &description "Undergraduate, Wuhan University · Discrete convexity, optimization, algorithms"
url         : "https://leoway2005.github.io"   # 你的主页域名
baseurl     : ""                               # 不要改
repository  : "leoway2005/leoway2005.github.io"

# --- Author block（侧边个人信息）---
author:
  avatar     : "images/profile.png"   # 头像文件放到 images/ 目录，名字可改
  name       : "Ling Aowei (凌奥炜)"
  bio        : "Undergraduate in Mathematics, Wuhan University. I study discrete convexity on cycles and related envelope algorithms."
  location   : "Wuhan, China"
  employer   : "Wuhan University"
  email      : "yourname@whu.edu.cn"   # 没有就先留空或用常用邮箱
  uri        : "https://leoway2005.github.io"

  # Academic profiles（有就填链接，没有先留空）
  arxiv            : ""    # 例如：https://arxiv.org/a/XXXX.html 或具体论文页
  googlescholar    : ""    # 申请后填你的 Scholar 链接
  orcid            : ""    # 例如：https://orcid.org/0000-0000-0000-0000
  researchgate     : ""
  semantic         : ""
  pubmed           : ""
  scopus           : ""

  # Code/Social（按需填）
  github           : "leoway2005"
  linkedin         : ""    # 例如：https://www.linkedin.com/in/xxxx
  twitter          : ""    # X/Twitter 用户名或链接
  zhihu            : ""    # 知乎用户名或主页链接
  bluesky          : ""    # 有再填

# --- Publication Category 名称（保持即可，也可自定义中文）---
publication_category:
  books:         { title: "Books" }
  manuscripts:   { title: "Journal Articles" }
  conferences:   { title: "Conference Papers" }

# --- 站点设置：保持默认即可，下面只改两处小东西 ---
comments:
  provider: false   # 不想开评论就关掉，干净

analytics:
  provider: "false" # 暂时不开统计，后续要用可填 google-analytics-4

# --- 包含/集合/默认渲染 这些都保持不动 ---
